name: chili_debug_view
description: Flutter debug view for network logs
homepage: https://github.com/ChiliLabs/chili_debug_view
version: 1.0.0

topics:
  - debug
  - dio
  - network
  - logs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  dio: any
  share_plus: any
  path_provider: any

flutter:
  uses-material-design: true
