name: chili_debug_view
description: Flutter debug view for checking network logs, response time and sharing them outside of app
homepage: https://github.com/ChiliLabs/chili_debug_view
version: 1.1.0

topics:
  - debug
  - dio
  - network
  - logs

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.19.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  share_plus: ^10.1.4
  path_provider: ^2.1.5

flutter:
  uses-material-design: true
